Issue 1321: update amethyst.sample.yml include all defaults
ianyh/Amethyst pull request #1326
Opened 2022-10-19 21:40 UTC by wley3337

Update `amethyst.sample.yml` to include all the defaults and the text description of what they do

2022-12-01 11:49 UTC, goodshort requested changes
Few comments/suggested changes to make this starter config file a bit more resilient

2022-12-01 11:49 UTC, goodshort commented on .amethyst.sample.yml
> +# This removes the current preferences and causes a re-load of this file when amethyst restarts.
I don't know all the mechanics behind macOS and preferences, but I have been playing with preferences yesterday for thie issue #1348  and the `/Library/Preferences/com.amethyst.Amethyst.plist` file does not seem to always be generated (at least on my Mac mini macOS Ventura). However, you can reset your preferences using `defaults delete com.amethyst.Amethyst.plist`

```suggestion
# If you experience issues pulling in the changes you can also quit Amethyst and run: `defaults delete com.amethyst.Amethyst.plist`
# This removes the current preferences and causes Amethyst to restart with default preferences and pull configs from this file.
```

2022-12-01 11:49 UTC, goodshort commented on .amethyst.sample.yml
> +# "left"
AFAIK YAML requires quotes only for the special characters below:
```
: { } [ ] , & * # ? | - < > = ! % @ `
```

Just a matter of style and preferences I would use the below unquoted.

I would add `,` `.` as these are special characters implemented by default. And I would use single quote as best practice. (i.e. `"\"` breaks the config, but `'\'` doesn't. However, a simple `key: \` works too, as it is not considered a special character...)

```suggestion
# space
# enter
# up
# right
# down
# left

# special characters require quotes
# '.'
# ','
```

2022-12-01 11:49 UTC, goodshort commented on .amethyst.sample.yml
> +  key: "space"
Based on suggestion above
```suggestion
  key: space
```

2022-12-01 11:49 UTC, goodshort commented on .amethyst.sample.yml
> +  key: "space"
Based on suggestion above
```suggestion
  key: space
```

2022-12-01 11:49 UTC, goodshort commented on .amethyst.sample.yml
> +  key: ","
Based on suggestion above
```suggestion
  key: ','
```

2022-12-01 11:49 UTC, goodshort commented on .amethyst.sample.yml
> +  key: "."
Based on suggestion above
```suggestion
  key: '.'
```

2022-12-01 11:49 UTC, goodshort commented on .amethyst.sample.yml
> +  key: "enter"
Based on suggestion above
```suggestion
  key: enter
```

2022-12-01 11:49 UTC, goodshort commented on .amethyst.sample.yml
> +  key: "left"
Based on suggestion above
```suggestion
  key: left
```

2022-12-01 11:49 UTC, goodshort commented on .amethyst.sample.yml
> +  key: "right"
Based on suggestion above
```suggestion
  key: right
```

2022-12-01 12:18 UTC, goodshort requested changes
2 minor suggestion for better readability through an IDE

2022-12-01 12:18 UTC, goodshort commented on .amethyst.sample.yml
> +# layouts	Ordered list of layouts to use by layout key (default tall, wide, fullscreen, and column).
Tab confuses syntax highlighting
```suggestion
# layouts - Ordered list of layouts to use by layout key (default tall, wide, fullscreen, and column).
```

2022-12-01 12:18 UTC, goodshort commented on .amethyst.sample.yml
> +#	First mod (default option + shift).
Tab confuses syntax highlighting
```suggestion
# First mod (default option + shift).
```

2022-12-09 02:12 UTC, wley3337 commented
@goodshort Sorry for the delay and thank you so much for the review! I tested out with my local and the `"` around the commands are definitely not needed ( outside the special characters ). Accepted all the suggestions. It's odd though there was only a single space on my local version for the comments rather than a tab space. I wonder why that looked like an indent 🤷

2022-12-09 12:51 UTC, goodshort approved these changes, later dismissed
Works fine on my machine. File is now a lot more readable and well documented. Thanks @wley3337

2023-01-24 04:00 UTC, cowboy-bebug reviewed
Some defaults such as `select-*-layout` are missing from [default.amethyst](https://github.com/ianyh/Amethyst/blob/development/Amethyst/default.amethyst) 😃

2023-02-03 20:50 UTC, jabkoo commented
+1 for @cowboy-bebug suggestion. `select-*-layout` commands are not documented anywhere, so I would also like to see it mentioned in docs/configuration-files.md.

2023-02-11 13:07 UTC, wley3337 commented
Hi all! 

Been a bit swamped between work and life. Going to try and sort out the `select-*-layout` stuff in the next few days and get this updated

2023-02-12 20:29 UTC, Indyandie commented
@wley3337 please note that this bug (#1419) could affect some of the configs

2023-02-19 02:02 UTC, wley3337 commented
Hi all!

Thank you all for your comments and patience. @Indyandie I'm not sure how to handle the possible conflicts. I added a block comment at the top to help with troubleshooting. Other than that, the only thing I can think of is to comment out the default values that are in `default.amethyst` and add the comment on each of those lines.


Something like:
```yml
# Commented out to avoid conflicts with `default.amethyst`
# only uncomment if you're going to change the default value below
# Move to the next layout in the list
# cycle-layout:
#   mod: mod1
#   key: space
```

2023-03-14 12:21 UTC, ianyh commented
I might want to make some tweaks to this. Is it possible to give me permissions to push to this branch?

2023-03-25 22:53 UTC, vicmunoz commented
Thanks!
Only missing


window-max-count | The max number of windows that may be visible on a screen at one time before additional windows are minimized. A value of 0 disables the feature. (default 0)
-- | --

2023-04-09 20:05 UTC, prettymuchbryce commented
We should merge this. Even if it's incomplete it is already way better than the current sample file, and this PR has been open for nearly 6 months.

2023-04-09 23:13 UTC, wley3337 commented
Add the missing two defaults above and fixed typo

2023-04-09 23:15 UTC, wley3337 commented
Oh, @ianyh I __think__ I granted you access to push/pull let me know if that didn't work :) I pulled right before addressing the two comments so not sure if Github let you know :)

2023-06-03 00:38 UTC, ianyh approved these changes

2023-06-03 00:38 UTC, merged