Add mod3 and mod4 as modifier keys
ianyh/Amethyst pull request #1373
Opened 2023-01-17 04:17 UTC by rjuer

Closes #317

2023-01-17 16:02 UTC, ianyh commented
Cool. I'd rather not define them by default, though.

2023-01-17 16:34 UTC, rjuer commented
That's a very reasonable suggestion - I added the fix.

2023-01-20 02:50 UTC, ianyh requested changes

2023-01-20 02:50 UTC, ianyh commented on Amethyst/Preferences/UserConfiguration.swift
> +        let mod3Strings: [String] = configurationValueForKey(.mod3)!
Ah, I see why the `[]`. I think we can remove the lines from `default.amethyst` entirely and remove the force unwrap here? As it is now, technically something like `mod3+x` would just get triggered by `x`.

2023-01-20 17:13 UTC, ianyh requested changes

2023-01-20 17:13 UTC, ianyh commented on Amethyst/Preferences/UserConfiguration.swift
> +        if mod3Strings != nil {
The swift idiom here would be unwrapping.
```swift
if let modStrings = mod3Strings {
    // modStrings is a regular value in scope
}
```

2023-01-21 17:48 UTC, ianyh approved these changes

2023-01-21 17:48 UTC, merged

2023-01-21 17:48 UTC, ianyh commented
Thanks for the contribution!