When adding windows use the previous main as last focused
ianyh/Amethyst pull request #1397
Opened 2023-01-31 13:06 UTC by rickythefox

When adding a new window with the "Send new windows to main pane" setting active, we should save the previous main window.

Sorry for spamming PRs on this topic.

2023-01-31 16:02 UTC, ianyh requested changes

2023-01-31 16:02 UTC, ianyh commented on Amethyst/Managers/Windows.swift
> +        func activeWindowsOnCurrentScreen() -> (Space, [Window])? {
I understand the convenience of returning the tuple, but I would prefer the space call to be separate.

2023-01-31 19:25 UTC, rickythefox commented on Amethyst/Managers/Windows.swift
> +        func activeWindowsOnCurrentScreen() -> (Space, [Window])? {
Done

2023-02-01 13:54 UTC, ianyh approved these changes

2023-02-01 13:54 UTC, merged