Add section on building locally to README. Fix app version.
ianyh/Amethyst pull request #1663
Opened 2024-06-19 15:56 UTC by x-ji

- [Add README section on building Amethyst locally](https://github.com/ianyh/Amethyst/commit/c1c24ed29e7e96aec243e744c96f75937c3469cf)
- [Add explanation to the Configuration File README section](https://github.com/ianyh/Amethyst/commit/f15d71e937769db5cdbd7ec0d8c1d88f32633d3d)
- [Bump app version according to the latest release](https://github.com/ianyh/Amethyst/commit/7a35160f6d90880a860a4ea4ff5bd42f90fe2bdb)

2024-06-19 15:59 UTC, x-ji commented
I realized the app version seems outdated so that I tried to find it and update that as well. Let me know if that's the right place.

2024-06-19 16:00 UTC, x-ji commented
Let me know if it makes sense to keep these changes in the same MR or if it would be better to open multiple MRs for them.

2024-09-27 00:27 UTC, ianyh requested changes

2024-09-27 00:27 UTC, ianyh commented on Amethyst.xcodeproj/project.pbxproj
> +				MARKETING_VERSION = 0.21.1;
Could you remove this part?

2025-01-09 00:36 UTC, gplusplus314 commented
I just landed here after trying to build locally. I don't typically code within Apple's ecosystem, so it took me a while to figure out that I had to `brew install swiftlint` to get the build to work. For reasons I do not understand, it succeeds in XCode, but not with Fastlane. I'm not too familiar with this toolchain, so unfortunately, I don't really have any better insights other than there are more details and steps missing from the `README` than what is included in this PR. Hope that helps!

2025-01-21 01:50 UTC, closed without merging

2025-01-28 08:19 UTC, x-ji commented
Sorry, it seems that I missed the comment. Not sure how I ended up including an extra change. Thanks for incorporating the change! @ianyh 🙌